version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  drift-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.drift
    depends_on:
      - kafka
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dashboard
    depends_on:
      - drift-monitor
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
