log_source:
  type: kafka
  topic: log-stream
  bootstrap_servers: kafka:9092
  group_id: log-sentinel
drift_history_file_path: data/processed/drift_history.csv
log_file_path: logs/app.log
drift_patience: 3
window_size: 1000
overlap: 0.4
drift_threshold: 0.1
bert_model: all-MiniLM-L6-v2