log_file_path: ../data/raw/hadoop-hdfs-datanode-mesos-32.log
drift_history_file_path: ../data/processed/drift_history.csv
window_size: 1000
overlap: 0.4
drift_threshold: 0.1
bert_model: all-MiniLM-L6-v2